# Activity: The "Hospital Pharmacy Inventory Manager"

### Activity Type:
Online

### Objective:
To master the end-to-end data workflow including loading external datasets, handling missing values, performing data cleaning, creating new features, filtering records, generating analytical reports, and exporting cleaned data.

---

## Steps

### 1. File Creation & Loading

- Use **medicine_inventory.csv**.
- Load the file into a DataFrame using `pd.read_csv()`.

---

### 2. Initial Exploration

- Display the first **5** rows and the last **2** rows of the dataset.
- Check the number of missing values in the **Price** and **Quantity** columns.

---

### 3. Data Cleaning

- Fill the missing values in **Price** with the **mean (average) price**.
- Fill any missing values in **Quantity** with **1**.

---

### 4. Feature Engineering

- Create a new column called **Inventory_Value** using the following formula:

> **Inventory_Value = Price × Quantity**

---

### 5. Filtering & Slicing

#### Boolean Filtering

Create a new DataFrame called **well_stocked** that contains medicines with a **Quantity of 15 or more**.

#### loc Selection

Display rows **5 to 10** and show only the following columns:

- Medicine
- Inventory_Value

---

### 6. Reporting

Use `.describe()` to generate a statistical summary of the **Inventory_Value** column.

---

### 7. Final Step

Save the cleaned dataset into a new CSV file called:

`cleaned_medicine_inventory.csv`

using the `.to_csv()` method.

In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv(r"Medicine.csv")

In [2]:
print(df.head())
print(df.tail(2))
print(df["Price"].isna().sum())
print(df["Quantity"].isna().sum())

      Medicine  Price  Quantity     Category
0  Paracetamol   25.0      20.0  Pain Relief
1    Ibuprofen   35.0       NaN  Pain Relief
2  Amoxicillin   80.0      12.0  Antibiotics
3    Vitamin C   50.0      30.0  Supplements
4      Insulin    NaN       5.0     Diabetes
               Medicine  Price  Quantity     Category
13  Glucose Test Strips   90.0      18.0     Diabetes
14        Multivitamins   40.0      22.0  Supplements
1
3

In [3]:
df["Price"]=df["Price"].fillna(df["Price"].mean())
df["Quantity"]=df["Quantity"].fillna(1)
print(df["Price"].isna().sum())
print(df["Quantity"].isna().sum())

0
0

In [4]:
df["Inventory_Value"]=df["Price"]*df["Quantity"]
df

,Medicine,Price,Quantity,Category,Inventory_Value
0,Paracetamol,25.000000,20.0,Pain Relief,500.000000
1,Ibuprofen,35.000000,1.0,Pain Relief,35.000000
2,Amoxicillin,80.000000,12.0,Antibiotics,960.000000
3,Vitamin C,50.000000,30.0,Supplements,1500.000000
4,Insulin,61.785714,5.0,Diabetes,308.928571
5,Cough Syrup,65.000000,8.0,Cold & Flu,520.000000
6,Antacid,30.000000,15.0,Digestive,450.000000
7,Eye Drops,45.000000,1.0,Eye Care,45.000000
8,Bandages,10.000000,50.0,First Aid,500.000000
9,Hand Sanitizer,20.000000,25.0,Hygiene,500.000000
10,Face Mask,5.000000,100.0,Hygiene,500.000000
11,Thermometer,120.000000,6.0,Medical Equipment,720.000000
12,Blood Pressure Monitor,250.000000,1.0,Medical Equipment,250.000000
13,Glucose Test Strips,90.000000,18.0,Diabetes,1620.000000
14,Multivitamins,40.000000,22.0,Supplements,880.000000

In [5]:
well_stocked=df[df["Quantity"]>=15]
print(well_stocked)
df.loc[5:10,["Medicine","Inventory_Value"]]

               Medicine  Price  Quantity     Category  Inventory_Value
0           Paracetamol   25.0      20.0  Pain Relief            500.0
3             Vitamin C   50.0      30.0  Supplements           1500.0
6               Antacid   30.0      15.0    Digestive            450.0
8              Bandages   10.0      50.0    First Aid            500.0
9        Hand Sanitizer   20.0      25.0      Hygiene            500.0
10            Face Mask    5.0     100.0      Hygiene            500.0
13  Glucose Test Strips   90.0      18.0     Diabetes           1620.0
14        Multivitamins   40.0      22.0  Supplements            880.0

          Medicine  Inventory_Value
5      Cough Syrup            520.0
6          Antacid            450.0
7        Eye Drops             45.0
8         Bandages            500.0
9   Hand Sanitizer            500.0
10       Face Mask            500.0

In [6]:
df["Inventory_Value"].describe()

count      15.000000
mean      619.261905
std       460.636769
min        35.000000
25%       379.464286
50%       500.000000
75%       800.000000
max      1620.000000
Name: Inventory_Value, dtype: float64

In [9]:
df.to_csv("cleaned_medicine_inventory.csv", index=False)

In [10]:
df1=pd.read_csv(r"cleaned_medicine_inventory.csv")
df1.shape

(15, 5)