# 🐼 Pandas — Code Lab (Part 2 of 2)
### Lecture 03 · Sections 10–18
Continues directly from Part 1. We rebuild the same `employees` dataset (in the same state it ended Part 1 in) so everything stays consistent, then finish with the real **Titanic** dataset for the Mini Project.

## Rebuilding `employees` (continuing from Part 1)

In [2]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 102],  # 102 repeated on purpose
    "Name": ["Sara", "Omar", "Lina", "Ahmed", "Farida", "Youssef", "Mona", "Karim", "Salma", "Omar"],
    "Department": ["IT", "Sales", "IT", "HR", "Sales", "IT", "HR", "Sales", "IT", "Sales"],
    "City": ["Cairo", "Giza", "Cairo", "Alex", "Cairo", "Giza", "Alex", "Cairo", "Giza", "Giza"],
    "Salary": [9000, 7000, 8500, 6000, 7200, 9500, 6100, 7300, 8800, 7000],
    "YearsExperience": [5, 3, 6, 2, 4, 7, 1, 3, 5, 3],
    "PerformanceScore": [88, 75, np.nan, 65, 90, np.nan, 70, 82, np.nan, 75],
})
employees["YearsExperience"] = employees["YearsExperience"].astype(float)
employees["Bonus"] = employees["Salary"] * 0.1
employees["SalaryK"] = employees["Salary"] / 1000
employees["SalaryAfterRaise"] = employees["Salary"] * 1.05

df = employees
df

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore,Bonus,SalaryK,SalaryAfterRaise
0,101,Sara,IT,Cairo,9000,5.0,88.0,900.0,9.0,9450.0
1,102,Omar,Sales,Giza,7000,3.0,75.0,700.0,7.0,7350.0
2,103,Lina,IT,Cairo,8500,6.0,NaN,850.0,8.5,8925.0
3,104,Ahmed,HR,Alex,6000,2.0,65.0,600.0,6.0,6300.0
4,105,Farida,Sales,Cairo,7200,4.0,90.0,720.0,7.2,7560.0
5,106,Youssef,IT,Giza,9500,7.0,NaN,950.0,9.5,9975.0
6,107,Mona,HR,Alex,6100,1.0,70.0,610.0,6.1,6405.0
7,108,Karim,Sales,Cairo,7300,3.0,82.0,730.0,7.3,7665.0
8,109,Salma,IT,Giza,8800,5.0,NaN,880.0,8.8,9240.0
9,102,Omar,Sales,Giza,7000,3.0,75.0,700.0,7.0,7350.0

## 10. Duplicate Data

We put a duplicate row in on purpose (`Omar`, EmployeeID 102, appears twice).

In [3]:
df.duplicated()          # Boolean mask: True where a row is an exact repeat of an earlier one

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
dtype: bool

In [4]:
df.duplicated().sum()    # how many duplicate rows total

np.int64(1)

In [5]:
df[df.duplicated()]      # show the duplicate row(s)

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore,Bonus,SalaryK,SalaryAfterRaise
9,102,Omar,Sales,Giza,7000,3.0,75.0,700.0,7.0,7350.0

In [ ]:
print("before:", df.shape)
df = df.drop_duplicates()
print("after :", df.shape)

before: (10, 10)
after : (9, 10)

In [7]:
# checking duplicates on a SUBSET of columns (e.g. same EmployeeID even if other fields differ)
df.drop_duplicates(subset=["EmployeeID"])

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore,Bonus,SalaryK,SalaryAfterRaise
0,101,Sara,IT,Cairo,9000,5.0,88.0,900.0,9.0,9450.0
1,102,Omar,Sales,Giza,7000,3.0,75.0,700.0,7.0,7350.0
2,103,Lina,IT,Cairo,8500,6.0,NaN,850.0,8.5,8925.0
3,104,Ahmed,HR,Alex,6000,2.0,65.0,600.0,6.0,6300.0
4,105,Farida,Sales,Cairo,7200,4.0,90.0,720.0,7.2,7560.0
5,106,Youssef,IT,Giza,9500,7.0,NaN,950.0,9.5,9975.0
6,107,Mona,HR,Alex,6100,1.0,70.0,610.0,6.1,6405.0
7,108,Karim,Sales,Cairo,7300,3.0,82.0,730.0,7.3,7665.0
8,109,Salma,IT,Giza,8800,5.0,NaN,880.0,8.8,9240.0

**✍️ Practice 10**
1. Confirm there are now 0 duplicate rows in `df`.
2. Create a tiny test DataFrame with 2 identical rows and 1 different row, then drop duplicates on it.

In [8]:
# ✅ solution
print(df.duplicated().sum())

test = pd.DataFrame({"a": [1, 1, 2], "b": [2, 2, 3]})
print(test.drop_duplicates())

0
   a  b
0  1  2
2  2  3

## 11. Grouping & Aggregation

`groupby()` follows **split → apply → combine**: split rows into groups by a column, apply a calculation to each group, combine results into one table.

In [9]:
df.groupby("Department")["Salary"].mean()

Department
HR       6050.000000
IT       8950.000000
Sales    7166.666667
Name: Salary, dtype: float64

**🔮 Predict the Output:** which department do you expect to have the highest average salary, based on eyeballing the table above?

In [10]:
df.groupby("Department")["Salary"].mean().round(2).sort_values(ascending=False)

Department
IT       8950.00
Sales    7166.67
HR       6050.00
Name: Salary, dtype: float64

In [11]:
df.groupby("Department")["Salary"].sum()
df.groupby("Department")["Salary"].count()
df.groupby("Department")["Salary"].min()
df.groupby("Department")["Salary"].max()
df.groupby("Department")["Salary"].std()

Department
HR        70.710678
IT       420.317340
Sales    152.752523
Name: Salary, dtype: float64

In [12]:
# .agg() -- multiple aggregations at once, and DIFFERENT functions per column
df.groupby("Department").agg({
    "Salary": "mean",
    "YearsExperience": "max",
    "EmployeeID": "count"
})

                 Salary  YearsExperience  EmployeeID
Department
HR          6050.000000              2.0           2
IT          8950.000000              7.0           4
Sales       7166.666667              4.0           3

In [13]:
df.groupby("Department")["Salary"].agg(["sum", "mean", "count"])

              sum         mean  count
Department
HR          12100  6050.000000      2
IT          35800  8950.000000      4
Sales       21500  7166.666667      3

In [14]:
# multiple-column grouping
df.groupby(["Department", "City"])["Salary"].mean()

Department  City
HR          Alex     6050.0
IT          Cairo    8750.0
            Giza     9150.0
Sales       Cairo    7250.0
            Giza     7000.0
Name: Salary, dtype: float64

**✍️ Practice 11**
1. Average `YearsExperience` per `Department`.
2. For each `Department`, get `min`, `max`, and `mean` of `Salary` in one call using `.agg()`.
3. Group by `["Department", "City"]` and count employees in each group.

In [15]:
# ✅ solution
print(df.groupby("Department")["YearsExperience"].mean())
print(df.groupby("Department")["Salary"].agg(["min", "max", "mean"]))
print(df.groupby(["Department", "City"])["EmployeeID"].count())

Department
HR       1.500000
IT       5.750000
Sales    3.333333
Name: YearsExperience, dtype: float64
             min   max         mean
Department
HR          6000  6100  6050.000000
IT          8500  9500  8950.000000
Sales       7000  7300  7166.666667
Department  City
HR          Alex     2
IT          Cairo    2
            Giza     2
Sales       Cairo    2
            Giza     1
Name: EmployeeID, dtype: int64

## 12. Combining DataFrames

In [56]:
print(df)
departments = pd.DataFrame({
    "Department": ["IT", "Sales", "HR", "Finance"],   # Finance has no employees in df, on purpose
    "Manager": ["Nadia", "Hassan", "Rana", "Tarek"],
    "Budget": [500000, 350000, 200000, 150000],
})
departments

   EmployeeID     Name Department   City  Salary  YearsExperience  \
0         101     Sara         IT  Cairo    9000              5.0
1         102     Omar      Sales   Giza    7000              3.0
2         103     Lina         IT  Cairo    8500              6.0
3         104    Ahmed         HR   Alex    6000              2.0
4         105   Farida      Sales  Cairo    7200              4.0
5         106  Youssef         IT   Giza    9500              7.0
6         107     Mona         HR   Alex    6100              1.0
7         108    Karim      Sales  Cairo    7300              3.0
8         109    Salma         IT   Giza    8800              5.0

   PerformanceScore  Bonus  SalaryK  SalaryAfterRaise  Salary_plus_Bonus  \
0              88.0  900.0      9.0            9450.0             9900.0
1              75.0  700.0      7.0            7350.0             7700.0
2               NaN  850.0      8.5            8925.0             9350.0
3              65.0  600.0      6.0            6300.0             6600.0
4              90.0  720.0      7.2            7560.0             7920.0
5               NaN  950.0      9.5            9975.0            10450.0
6              70.0  610.0      6.1            6405.0             6710.0
7              82.0  730.0      7.3            7665.0             8030.0
8               NaN  880.0      8.8            9240.0             9680.0

   HighEarner  ExperienceAfter5Years         Region
0        True                   10.0  Greater Cairo
1       False                    8.0  Greater Cairo
2        True                   11.0  Greater Cairo
3       False                    7.0          Delta
4       False                    9.0  Greater Cairo
5        True                   12.0  Greater Cairo
6       False                    6.0          Delta
7       False                    8.0  Greater Cairo
8        True                   10.0  Greater Cairo

  Department Manager  Budget
0         IT   Nadia  500000
1      Sales  Hassan  350000
2         HR    Rana  200000
3    Finance   Tarek  150000

In [17]:
merged = pd.merge(df, departments, on="Department", how="left")
merged[["Name", "Department", "Manager", "Budget"]]

      Name Department Manager  Budget
0     Sara         IT   Nadia  500000
1     Omar      Sales  Hassan  350000
2     Lina         IT   Nadia  500000
3    Ahmed         HR    Rana  200000
4   Farida      Sales  Hassan  350000
5  Youssef         IT   Nadia  500000
6     Mona         HR    Rana  200000
7    Karim      Sales  Hassan  350000
8    Salma         IT   Nadia  500000

### Join types

| Join | Keeps |
|---|---|
| `inner` | only rows that match in **both** tables |
| `left` | all rows from the left table, matched where possible |
| `right` | all rows from the right table, matched where possible |
| `outer` | all rows from **both** tables |

In [18]:
inner = pd.merge(df, departments, on="Department", how="inner")
outer = pd.merge(df, departments, on="Department", how="outer")

print("inner shape:", inner.shape, "-> Finance dropped (no employees)")
print("outer shape:", outer.shape, "-> Finance kept, with NaN employee fields")
outer[outer["Department"] == "Finance"]

inner shape: (9, 12) -> Finance dropped (no employees)
outer shape: (10, 12) -> Finance kept, with NaN employee fields

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore,Bonus,SalaryK,SalaryAfterRaise,Manager,Budget
0,NaN,NaN,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tarek,150000

In [19]:
# concat() -- stacking, NOT matching by key
new_hires_q1 = pd.DataFrame({
    "EmployeeID": [110, 111],
    "Name": ["Farida2", "Tamer"],
    "Department": ["IT", "Sales"],
    "City": ["Cairo", "Giza"],
    "Salary": [8000, 7500],
})
stacked = pd.concat([df[["EmployeeID", "Name", "Department", "City", "Salary"]], new_hires_q1], axis=0, ignore_index=True)
print(stacked.shape)
stacked.tail(4)

(11, 5)

    EmployeeID     Name Department   City  Salary
7          108    Karim      Sales  Cairo    7300
8          109    Salma         IT   Giza    8800
9          110  Farida2         IT  Cairo    8000
10         111    Tamer      Sales   Giza    7500

In [20]:
# horizontal concat -- side by side (must share the same index alignment)
extra_info = pd.DataFrame({"Remote": [True, False, True, False, True, False, True, False, True]},
                           index=df.index)
pd.concat([df[["Name"]], extra_info], axis=1)

      Name  Remote
0     Sara    True
1     Omar   False
2     Lina    True
3    Ahmed   False
4   Farida    True
5  Youssef   False
6     Mona    True
7    Karim   False
8    Salma    True

**✍️ Practice 12**
1. Merge `df` with `departments` using `how="right"` and check the shape.
2. Which department(s) appear in `departments` but have zero employees in `df`? (hint: use an outer merge + `isna()`)
3. Stack `df` with `new_hires_q1` (vertically) and confirm total row count.

In [21]:
# ✅ solution
right = pd.merge(df, departments, on="Department", how="right")
print(right.shape)

check = pd.merge(df, departments, on="Department", how="outer")
print(check[check["Name"].isna()]["Department"].tolist())

combo = pd.concat([df, new_hires_q1], ignore_index=True)
print(combo.shape)

(10, 12)
['Finance']
(11, 10)

## 13. Pivot Tables

A quick way to summarize grouped data into a grid — `values` (what to summarize), `index` (rows), `columns` (optional second grouping), `aggfunc` (how).

In [22]:
pd.pivot_table(merged, values="Salary", index="Department", aggfunc="mean")

                 Salary
Department
HR          6050.000000
IT          8950.000000
Sales       7166.666667

In [23]:
pd.pivot_table(merged, values="Salary", index="Department", columns="City", aggfunc="mean")

City          Alex   Cairo    Giza
Department
HR          6050.0     NaN     NaN
IT             NaN  8750.0  9150.0
Sales          NaN  7250.0  7000.0

In [24]:
pd.pivot_table(merged, values="Salary", index="Department", aggfunc=["mean", "count"])

                   mean  count
                 Salary Salary
Department
HR          6050.000000      2
IT          8950.000000      4
Sales       7166.666667      3

**✍️ Practice 13**
1. Pivot table: average `YearsExperience` by `Department`.
2. Pivot table: average `Salary` by `Department` (rows) and `City` (columns), using `aggfunc="max"` instead of mean.

In [25]:
# ✅ solution
print(pd.pivot_table(df, values="YearsExperience", index="Department", aggfunc="mean"))
print(pd.pivot_table(merged, values="Salary", index="Department", columns="City", aggfunc="max"))

            YearsExperience
Department
HR                 1.500000
IT                 5.750000
Sales              3.333333
City          Alex   Cairo    Giza
Department
HR          6100.0     NaN     NaN
IT             NaN  9000.0  9500.0
Sales          NaN  7300.0  7000.0

## 14. Applying Functions

`.apply()` runs a function over every value in a Series (or every row/column of a DataFrame) — for logic that built-in Pandas functions don't cover.

In [26]:
df["Name"].apply(len)          # built-in function, applied element by element

0    4
1    4
2    4
3    5
4    6
5    7
6    4
7    5
8    5
Name: Name, dtype: int64

In [27]:
df["Salary"].apply(lambda x: x * 1.1)     # lambda -- an inline, throwaway function

0     9900.0
1     7700.0
2     9350.0
3     6600.0
4     7920.0
5    10450.0
6     6710.0
7     8030.0
8     9680.0
Name: Salary, dtype: float64

In [28]:
# apply() on a whole ROW (axis=1) -- useful when a calculation needs more than one column
df["Salary_plus_Bonus"] = df.apply(lambda row: row["Salary"] + row["Bonus"], axis=1)
df[["Name", "Salary", "Bonus", "Salary_plus_Bonus"]]

      Name  Salary  Bonus  Salary_plus_Bonus
0     Sara    9000  900.0             9900.0
1     Omar    7000  700.0             7700.0
2     Lina    8500  850.0             9350.0
3    Ahmed    6000  600.0             6600.0
4   Farida    7200  720.0             7920.0
5  Youssef    9500  950.0            10450.0
6     Mona    6100  610.0             6710.0
7    Karim    7300  730.0             8030.0
8    Salma    8800  880.0             9680.0

In [29]:
# creating new boolean/derived features
df["HighEarner"] = df["Salary"] >= 8000
df["ExperienceAfter5Years"] = df["YearsExperience"] + 5
df[["Name", "Salary", "HighEarner", "YearsExperience", "ExperienceAfter5Years"]]

      Name  Salary  HighEarner  YearsExperience  ExperienceAfter5Years
0     Sara    9000        True              5.0                   10.0
1     Omar    7000       False              3.0                    8.0
2     Lina    8500        True              6.0                   11.0
3    Ahmed    6000       False              2.0                    7.0
4   Farida    7200       False              4.0                    9.0
5  Youssef    9500        True              7.0                   12.0
6     Mona    6100       False              1.0                    6.0
7    Karim    7300       False              3.0                    8.0
8    Salma    8800        True              5.0                   10.0

**✍️ Practice 14**
1. Use `.apply()` to create a column with the **length** of each `Department` name.
2. Use a lambda with `.apply()` to flag `True`/`False` whether `YearsExperience` is above the average.
3. Use row-wise `.apply(axis=1)` to compute `Salary / (YearsExperience + 1)` (a rough "salary per year" metric).

In [30]:
# ✅ solution
print(df["Department"].apply(len))
avg_exp = df["YearsExperience"].mean()
print(df["YearsExperience"].apply(lambda x: x > avg_exp))
print(df.apply(lambda row: row["Salary"] / (row["YearsExperience"] + 1), axis=1).round(1))

0    2
1    5
2    2
3    2
4    5
5    2
6    2
7    5
8    2
Name: Department, dtype: int64
0     True
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8     True
Name: YearsExperience, dtype: bool
0    1500.0
1    1750.0
2    1214.3
3    2000.0
4    1440.0
5    1187.5
6    3050.0
7    1825.0
8    1466.7
dtype: float64

## 15. Mapping Values

`.map()` replaces values using a dictionary — simpler and faster than `.apply()` when you're just doing a **lookup/substitution**, not a calculation.

In [31]:
dept_full_name = {
    "IT": "Information Technology",
    "Sales": "Sales Department",
    "HR": "Human Resources"
}
df["Department"].map(dept_full_name)

0    Information Technology
1          Sales Department
2    Information Technology
3           Human Resources
4          Sales Department
5    Information Technology
6           Human Resources
7          Sales Department
8    Information Technology
Name: Department, dtype: str

In [32]:
city_region = {"Cairo": "Greater Cairo", "Giza": "Greater Cairo", "Alex": "Delta"}
df["Region"] = df["City"].map(city_region)
df[["Name", "City", "Region"]]

      Name   City         Region
0     Sara  Cairo  Greater Cairo
1     Omar   Giza  Greater Cairo
2     Lina  Cairo  Greater Cairo
3    Ahmed   Alex          Delta
4   Farida  Cairo  Greater Cairo
5  Youssef   Giza  Greater Cairo
6     Mona   Alex          Delta
7    Karim  Cairo  Greater Cairo
8    Salma   Giza  Greater Cairo

### `apply()` vs `map()`

| | `apply()` | `map()` |
|---|---|---|
| Use for | calculations, custom logic | value replacement/lookup |
| Input | any function or lambda | usually a dict (or a Series) |
| Flexibility | high | simpler, faster for substitutions |

**✍️ Practice 15**
1. Map `Department` to a short code: `{"IT":"T","Sales":"S","HR":"H"}`.
2. Map `City` to a boolean "IsCapitalArea" (`True` for Cairo/Giza, `False` otherwise) — you can do this with `.map()` and a dict, or `.isin()`. Try the `.map()` version.

In [33]:
# ✅ solution
print(df["Department"].map({"IT": "T", "Sales": "S", "HR": "H"}))
print(df["City"].map({"Cairo": True, "Giza": True, "Alex": False}))

0    T
1    S
2    T
3    H
4    S
5    T
6    H
7    S
8    T
Name: Department, dtype: str
0     True
1     True
2     True
3    False
4     True
5     True
6    False
7     True
8     True
Name: City, dtype: bool

## 16. Useful Pandas Functions

In [34]:
df["Department"].value_counts()      # frequency of each unique value, sorted descending

Department
IT       4
Sales    3
HR       2
Name: count, dtype: int64

In [35]:
df["City"].unique()        # array of distinct values (order = first appearance)

<StringArray>
['Cairo', 'Giza', 'Alex']
Length: 3, dtype: str

**✍️ Practice 16**
1. How many unique `City` values are there?
2. What's the most common `Department`?
3. What percentage of employees are in `IT`?

In [38]:
# ✅ solution
print(df["City"].nunique())
print(df["Department"].value_counts().idxmax())
print(df["Department"].value_counts(normalize=True).round(2)["IT"])

3
IT
0.44

## 17. Putting It All Together

One combined exercise using everything from Sections 10–16 on the `employees` dataset, before we move to the real-world Mini Project.

**✍️ Practice 17**
1. Remove duplicates from a fresh copy of the ORIGINAL data (re-load `employees.csv` from Part 1's folder if available, or reuse `df`).
2. Group by `Department`, get mean `Salary` and mean `YearsExperience` together via `.agg()`.
3. Merge with `departments` to add `Manager` names.
4. Pivot: average `Salary` by `Department` x `Region`.
5. Use `.map()` to create a short `Dept_Code` column.
6. Use `value_counts()` to find the most common `Region`.

In [39]:
# ✅ solution
step1 = df.drop_duplicates()
step2 = step1.groupby("Department").agg({"Salary": "mean", "YearsExperience": "mean"}).round(1)
print(step2)

step3 = pd.merge(step1, departments, on="Department", how="left")
print(step3[["Name", "Department", "Manager"]].head())

step4 = pd.pivot_table(step3, values="Salary", index="Department", columns="Region", aggfunc="mean")
print(step4)

step3["Dept_Code"] = step3["Department"].map({"IT": "T", "Sales": "S", "HR": "H"})
print(step3[["Name", "Dept_Code"]].head())

print(step3["Region"].value_counts())

            Salary  YearsExperience
Department
HR          6050.0              1.5
IT          8950.0              5.8
Sales       7166.7              3.3
     Name Department Manager
0    Sara         IT   Nadia
1    Omar      Sales  Hassan
2    Lina         IT   Nadia
3   Ahmed         HR    Rana
4  Farida      Sales  Hassan
Region       Delta  Greater Cairo
Department
HR          6050.0            NaN
IT             NaN    8950.000000
Sales          NaN    7166.666667
     Name Dept_Code
0    Sara         T
1    Omar         S
2    Lina         T
3   Ahmed         H
4  Farida         S
Region
Greater Cairo    7
Delta            2
Name: count, dtype: int64

## 18. Mini Project — The Titanic Dataset

We switch to a **real** dataset now: 891 real passenger records from the Titanic, with the famous `Survived` column (0 = No, 1 = Yes). Every technique from this notebook gets applied here.

## 🎉 End of Notebook

**Covered across both parts:** Series/DataFrame → Reading → Exploring → Selecting → Filtering → Sorting → Column creation/modification → Missing data → Duplicates → GroupBy/Aggregation → Merge/Concat → Pivot Tables → apply() → map() → value_counts/unique/nunique → a full real-world Titanic mini project.

**Next up (per the slides):** Exploratory Data Analysis (EDA) and data visualization.