# 🐼 Pandas — Code Lab (Part 1 of 2)
### Lecture 03 · Sections 1–9
Hands-on notebook: short explanation → runnable example → practice exercise → solution, for every concept.
One consistent teaching dataset (`employees`) is used throughout. Part 2 will cover Sections 10–18, ending with the real Titanic Mini Project.

## 1. Introduction

**What is Pandas?** A Python library for working with **structured (tabular) data** — rows and columns, like Excel or a SQL table, but programmable.

**Why not just NumPy?** NumPy arrays only hold **one data type** and have no labels. Pandas adds **labeled rows/columns** and lets each column have its **own dtype** — exactly what real-world data (mixed text + numbers) needs.

| | NumPy | Pandas |
|---|---|---|
| Structure | array (matrix) | labeled table |
| Best for | numeric computation | data analysis / cleaning |
| Built on | — | NumPy |

In [1]:
import pandas as pd
import numpy as np

print("pandas version:", pd.__version__)

pandas version: 3.0.3

In [2]:
# Quick NumPy vs Pandas contrast
arr = np.array([21, 22, 20])
s = pd.Series([21, 22, 20], index=["Sara", "Ali", "Omar"])

print("NumPy array (no labels):\n", arr)
print("\nPandas Series (labeled):\n", s)

NumPy array (no labels):
 [21 22 20]

Pandas Series (labeled):
 Sara    21
Ali     22
Omar    20
dtype: int64

## 2. Pandas Data Structures

### 2.1 Series — a single labeled column

In [3]:
ages = pd.Series([21, 22, 20, 23])
print(ages)
print(type(ages))

0    21
1    22
2    20
3    23
dtype: int64
<class 'pandas.Series'>

Notice the left column — that's the **index** (auto-generated: 0,1,2,3 by default).

In [4]:
# Custom index -- give each value a meaningful label instead of 0,1,2,3
gpa = pd.Series([3.8, 3.5, 3.9], index=["Sara", "Ali", "Omar"])
print(gpa)

# from a dict -- keys automatically become the index
gpa_dict = pd.Series({"Sara": 3.8, "Ali": 3.5, "Omar": 3.9})
print(gpa_dict)

Sara    3.8
Ali     3.5
Omar    3.9
dtype: float64
Sara    3.8
Ali     3.5
Omar    3.9
dtype: float64

In [5]:
# Accessing elements
print(gpa["Sara"])          # by label
print(gpa.iloc[0])          # by position
print(gpa.iloc[0:2])        # slice by position
print(gpa[["Sara", "Omar"]])  # multiple labels

3.8
3.8
Sara    3.8
Ali     3.5
dtype: float64
Sara    3.8
Omar    3.9
dtype: float64

In [6]:
# Series attributes
print("index :", gpa.index)
print("values:", gpa.values)      # returns a NumPy array underneath!
print("dtype :", gpa.dtype)
print("shape :", gpa.shape)
print("size  :", gpa.size)
print("ndim  :", gpa.ndim)

index : Index(['Sara', 'Ali', 'Omar'], dtype='str')
values: [3.8 3.5 3.9]
dtype : float64
shape : (3,)
size  : 3
ndim  : 1

**✍️ Practice 2.1**
1. Create a Series of 4 cities with custom index `["p1","p2","p3","p4"]`.
2. Print its `dtype` and `shape`.
3. Access the 3rd element by position AND by label.

In [8]:
# ✅ solution
cities = pd.Series(["Cairo", "Giza", "Alex", "Luxor"], index=["p1", "p2", "p3", "p4"])
print(cities.dtype, cities.shape)
print(cities.iloc[2], "|", cities["p3"])

str (4,)
Alex | Alex

### 2.2 DataFrame — a full table

A DataFrame = **rows + columns + column names + an index**. Think of it as a dictionary of Series sharing the same index.

In [9]:
# From a dictionary (most common)
employees_small = pd.DataFrame({
    "Name": ["Sara", "Omar", "Lina"],
    "Department": ["IT", "Sales", "IT"],
    "Salary": [9000, 7000, 8500]
})
employees_small

   Name Department  Salary
0  Sara         IT    9000
1  Omar      Sales    7000
2  Lina         IT    8500

In [10]:
# From a list of lists + explicit column names
rows = [["Sara", "IT", 9000], ["Omar", "Sales", 7000], ["Lina", "IT", 8500]]
df_from_lists = pd.DataFrame(rows, columns=["Name", "Department", "Salary"])
df_from_lists

   Name Department  Salary
0  Sara         IT    9000
1  Omar      Sales    7000
2  Lina         IT    8500

In [11]:
# From a list of dictionaries (one dict = one row)
records = [
    {"Name": "Sara", "Department": "IT", "Salary": 9000},
    {"Name": "Omar", "Department": "Sales", "Salary": 7000},
]
df_from_records = pd.DataFrame(records)
df_from_records

   Name Department  Salary
0  Sara         IT    9000
1  Omar      Sales    7000

In [12]:
# From a NumPy array
arr2d = np.array([[1, 90], [2, 85], [3, 78]])
df_from_np = pd.DataFrame(arr2d, columns=["ID", "Score"])
df_from_np

   ID  Score
0   1     90
1   2     85
2   3     78

In [13]:
# Custom index on a DataFrame
df_custom_idx = pd.DataFrame(
    {"Salary": [9000, 7000, 8500]},
    index=["Sara", "Omar", "Lina"]
)
df_custom_idx

      Salary
Sara    9000
Omar    7000
Lina    8500

In [14]:
# DataFrame is really a dict of Series sharing the same index
print(type(employees_small["Name"]))
employees_small["Name"]

<class 'pandas.Series'>

0    Sara
1    Omar
2    Lina
Name: Name, dtype: str

In [15]:
# DataFrame properties
df = employees_small
print("shape  :", df.shape)
print("columns:", df.columns.tolist())
print("index  :", df.index.tolist())
print("dtypes :\n", df.dtypes)
print("size   :", df.size)
print("ndim   :", df.ndim)

shape  : (3, 3)
columns: ['Name', 'Department', 'Salary']
index  : [0, 1, 2]
dtypes :
 Name            str
Department      str
Salary        int64
dtype: object
size   : 9
ndim   : 2

**✍️ Practice 2.2**
1. Build a DataFrame of 3 products (`Name`, `Price`) using a list of dicts.
2. Print its `.shape` and `.dtypes`.
3. Rebuild the same table but using a NumPy array + `columns=`.

In [17]:
# ✅ solution
products = pd.DataFrame([
    {"Name": "Laptop", "Price": 25000},
    {"Name": "Mouse", "Price": 300},
    {"Name": "Keyboard", "Price": 700},
])
print(products.shape)
print(products.dtypes)

arr_products = np.array([["Laptop", 25000], ["Mouse", 300], ["Keyboard", 700]])
products_np = pd.DataFrame(arr_products, columns=["Name", "Price"])
products_np

(3, 2)
Name       str
Price    int64
dtype: object

       Name  Price
0    Laptop  25000
1     Mouse    300
2  Keyboard    700

## Our teaching dataset for Sections 3–9: `employees`

We'll build a slightly larger, messier dataset (missing values + a duplicate row on purpose) and use it for every section from here on.

In [18]:
employees = pd.DataFrame({
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 102],  # 102 repeated on purpose
    "Name": ["Sara", "Omar", "Lina", "Ahmed", "Farida", "Youssef", "Mona", "Karim", "Salma", "Omar"],
    "Department": ["IT", "Sales", "IT", "HR", "Sales", "IT", "HR", "Sales", "IT", "Sales"],
    "City": ["Cairo", "Giza", "Cairo", "Alex", "Cairo", "Giza", "Alex", "Cairo", "Giza", "Giza"],
    "Salary": [9000, 7000, 8500, 6000, 7200, 9500, 6100, 7300, 8800, 7000],
    "YearsExperience": [5, 3, 6, 2, 4, 7, 1, 3, 5, 3],
    "PerformanceScore": [88, 75, np.nan, 65, 90, np.nan, 70, 82, np.nan, 75],
})
employees

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
1,102,Omar,Sales,Giza,7000,3,75.0
2,103,Lina,IT,Cairo,8500,6,NaN
3,104,Ahmed,HR,Alex,6000,2,65.0
4,105,Farida,Sales,Cairo,7200,4,90.0
5,106,Youssef,IT,Giza,9500,7,NaN
6,107,Mona,HR,Alex,6100,1,70.0
7,108,Karim,Sales,Cairo,7300,3,82.0
8,109,Salma,IT,Giza,8800,5,NaN
9,102,Omar,Sales,Giza,7000,3,75.0

In [19]:
# save & reload as CSV so read_csv() in the next section has a real file to work with
employees.to_csv("employees.csv", index=False)
print("employees.csv written:", employees.shape)

employees.csv written: (10, 7)

## 3. Reading Data

`pd.read_csv()` is the most common way real projects load data.

In [20]:
df = pd.read_csv("employees.csv")
df.head()

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
1,102,Omar,Sales,Giza,7000,3,75.0
2,103,Lina,IT,Cairo,8500,6,NaN
3,104,Ahmed,HR,Alex,6000,2,65.0
4,105,Farida,Sales,Cairo,7200,4,90.0

In [21]:
# saving back out -- the index=False trap
df.to_csv("employees_v2.csv")              # forgot index=False
reloaded = pd.read_csv("employees_v2.csv")
print(reloaded.columns.tolist())            # notice the extra "Unnamed: 0" column

df.to_csv("employees_v3.csv", index=False)  # correct
reloaded_clean = pd.read_csv("employees_v3.csv")
print(reloaded_clean.columns.tolist())

['Unnamed: 0', 'EmployeeID', 'Name', 'Department', 'City', 'Salary', 'YearsExperience', 'PerformanceScore']
['EmployeeID', 'Name', 'Department', 'City', 'Salary', 'YearsExperience', 'PerformanceScore']

**✍️ Practice 3**
1. Save `df` to `"employees_practice.csv"` correctly (no extra index column).
2. Reload it into a new variable `df_check` and confirm `df_check.shape == df.shape`.

In [23]:
# ✅ solution
df.to_csv("employees_practice.csv", index=False)
df_check = pd.read_csv("employees_practice.csv")
print(df_check.shape == df.shape)

True

## 4. Exploring Data

Always inspect data before touching it.

In [24]:
df.head()        # first 5 rows by default

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
1,102,Omar,Sales,Giza,7000,3,75.0
2,103,Lina,IT,Cairo,8500,6,NaN
3,104,Ahmed,HR,Alex,6000,2,65.0
4,105,Farida,Sales,Cairo,7200,4,90.0

In [25]:
df.tail(3)        # last 3 rows

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
7,108,Karim,Sales,Cairo,7300,3,82.0
8,109,Salma,IT,Giza,8800,5,NaN
9,102,Omar,Sales,Giza,7000,3,75.0

In [26]:
df.sample(3)      # 3 RANDOM rows -- rerun this cell and they change

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
1,102,Omar,Sales,Giza,7000,3,75.0
4,105,Farida,Sales,Cairo,7200,4,90.0

In [27]:
print("shape  :", df.shape)
print("columns:", df.columns.tolist())
print("index  :", df.index.tolist())

shape  : (10, 7)
columns: ['EmployeeID', 'Name', 'Department', 'City', 'Salary', 'YearsExperience', 'PerformanceScore']
index  : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
df.dtypes

EmployeeID            int64
Name                    str
Department              str
City                    str
Salary                int64
YearsExperience       int64
PerformanceScore    float64
dtype: object

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        10 non-null     int64
 1   Name              10 non-null     str
 2   Department        10 non-null     str
 3   City              10 non-null     str
 4   Salary            10 non-null     int64
 5   YearsExperience   10 non-null     int64
 6   PerformanceScore  7 non-null      float64
dtypes: float64(1), int64(3), str(3)
memory usage: 692.0 bytes

In [30]:
df.describe()        # numeric columns only

       EmployeeID      Salary  YearsExperience  PerformanceScore
count   10.000000    10.00000        10.000000          7.000000
mean   104.700000  7640.00000         3.900000         77.857143
std      2.750757  1228.54928         1.852926          9.227289
min    101.000000  6000.00000         1.000000         65.000000
25%    102.250000  7000.00000         3.000000         72.500000
50%    104.500000  7250.00000         3.500000         75.000000
75%    106.750000  8725.00000         5.000000         85.000000
max    109.000000  9500.00000         7.000000         90.000000

**✍️ Practice 4**
1. How many rows and columns does `df` have?
2. Which column(s) have missing values, based on `.info()`?
3. What's the average `Salary` (read it off `.describe()`)?

In [33]:
# ✅ solution
print("rows, cols:", df.shape)
print("missing in PerformanceScore:", df["PerformanceScore"].isna().sum())
print("average salary:", df["Salary"].mean().round(1))

rows, cols: (10, 7)
missing in PerformanceScore: 3
average salary: 7640.0

## 5. Selecting Data

- Single column → `df["col"]` returns a **Series**
- Multiple columns → `df[["col1","col2"]]` returns a **DataFrame**
- `.loc[]` → by **label**
- `.iloc[]` → by **integer position**

In [34]:
print(type(df["Salary"]))
df["Salary"]

<class 'pandas.Series'>

0    9000
1    7000
2    8500
3    6000
4    7200
5    9500
6    6100
7    7300
8    8800
9    7000
Name: Salary, dtype: int64

In [35]:
print(type(df[["Name", "Salary"]]))
df[["Name", "Salary"]]

<class 'pandas.DataFrame'>

      Name  Salary
0     Sara    9000
1     Omar    7000
2     Lina    8500
3    Ahmed    6000
4   Farida    7200
5  Youssef    9500
6     Mona    6100
7    Karim    7300
8    Salma    8800
9     Omar    7000

In [36]:
print(df.loc[2, "Salary"])        # row labeled 2, column "Salary"
print(df.iloc[2, 4])                # row at position 2, column at position 4

8500
8500

In [37]:
df.iloc[0:3, [1, 4]]        # first 3 rows, columns at positions 1 and 4 (Name, Salary)

   Name  Salary
0  Sara    9000
1  Omar    7000
2  Lina    8500

In [38]:
df.loc[0:3, ["Name", "Department"]]     # loc slicing is INCLUSIVE of the end label

    Name Department
0   Sara         IT
1   Omar      Sales
2   Lina         IT
3  Ahmed         HR

**✍️ Practice 5**
1. Select just the `Department` column as a Series.
2. Select `Name` and `City` together as a DataFrame.
3. Using `.loc`, get the `Name` of the employee in row labeled 5.
4. Using `.iloc`, get rows 2 through 4 (inclusive) and columns 0-2.

In [40]:
# ✅ solution
print(df["Department"])
print(df[["Name", "City"]])
print(df.loc[5, "Name"])
print(df.iloc[2:5, 0:3])

0       IT
1    Sales
2       IT
3       HR
4    Sales
5       IT
6       HR
7    Sales
8       IT
9    Sales
Name: Department, dtype: str
      Name   City
0     Sara  Cairo
1     Omar   Giza
2     Lina  Cairo
3    Ahmed   Alex
4   Farida  Cairo
5  Youssef   Giza
6     Mona   Alex
7    Karim  Cairo
8    Salma   Giza
9     Omar   Giza
Youssef
   EmployeeID    Name Department
2         103    Lina         IT
3         104   Ahmed         HR
4         105  Farida      Sales

## 6. Filtering Data

A condition like `df["Salary"] > 8000` builds a **Boolean mask**; `df[mask]` keeps only the `True` rows.

In [41]:
df[df["Salary"] > 8000]

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
2,103,Lina,IT,Cairo,8500,6,NaN
5,106,Youssef,IT,Giza,9500,7,NaN
8,109,Salma,IT,Giza,8800,5,NaN

In [42]:
# combining conditions -- use & (and), | (or), ~ (not) -- ALWAYS wrap each condition in ()
df[(df["Department"] == "IT") & (df["YearsExperience"] >= 5)]

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
2,103,Lina,IT,Cairo,8500,6,NaN
5,106,Youssef,IT,Giza,9500,7,NaN
8,109,Salma,IT,Giza,8800,5,NaN

In [43]:
df[(df["Department"] == "IT") | (df["Department"] == "HR")]

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
2,103,Lina,IT,Cairo,8500,6,NaN
3,104,Ahmed,HR,Alex,6000,2,65.0
5,106,Youssef,IT,Giza,9500,7,NaN
6,107,Mona,HR,Alex,6100,1,70.0
8,109,Salma,IT,Giza,8800,5,NaN

In [44]:
df[~(df["Department"] == "IT")]     # NOT IT

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
1,102,Omar,Sales,Giza,7000,3,75.0
3,104,Ahmed,HR,Alex,6000,2,65.0
4,105,Farida,Sales,Cairo,7200,4,90.0
6,107,Mona,HR,Alex,6100,1,70.0
7,108,Karim,Sales,Cairo,7300,3,82.0
9,102,Omar,Sales,Giza,7000,3,75.0

In [45]:
df[df["Department"].isin(["IT", "HR"])]     # same idea as chained == / or, but cleaner

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
2,103,Lina,IT,Cairo,8500,6,NaN
3,104,Ahmed,HR,Alex,6000,2,65.0
5,106,Youssef,IT,Giza,9500,7,NaN
6,107,Mona,HR,Alex,6100,1,70.0
8,109,Salma,IT,Giza,8800,5,NaN

In [46]:
df[df["Salary"].between(7000, 9000)]     # inclusive on both ends

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
1,102,Omar,Sales,Giza,7000,3,75.0
2,103,Lina,IT,Cairo,8500,6,NaN
4,105,Farida,Sales,Cairo,7200,4,90.0
7,108,Karim,Sales,Cairo,7300,3,82.0
8,109,Salma,IT,Giza,8800,5,NaN
9,102,Omar,Sales,Giza,7000,3,75.0

**🔮 Predict the Output:** before running the next cell, guess how many rows `df[df["Salary"].between(7000, 9000) & (df["Department"] == "IT")]` will return.

In [47]:
df[df["Salary"].between(7000, 9000) & (df["Department"] == "IT")]

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
2,103,Lina,IT,Cairo,8500,6,NaN
8,109,Salma,IT,Giza,8800,5,NaN

**✍️ Practice 6**
1. Filter employees with `YearsExperience` less than 3.
2. Filter employees in `Sales` OR `HR`, using `isin()`.
3. Filter employees NOT in Cairo.
4. Combine: `Department == "IT"` AND `Salary > 8500`.

In [49]:
# ✅ solution
print(df[df["YearsExperience"] < 3])
print(df[df["Department"].isin(["Sales", "HR"])])
print(df[~(df["City"] == "Cairo")])
print(df[(df["Department"] == "IT") & (df["Salary"] > 8500)])

   EmployeeID   Name Department  City  Salary  YearsExperience  \
3         104  Ahmed         HR  Alex    6000                2
6         107   Mona         HR  Alex    6100                1

   PerformanceScore
3              65.0
6              70.0
   EmployeeID    Name Department   City  Salary  YearsExperience  \
1         102    Omar      Sales   Giza    7000                3
3         104   Ahmed         HR   Alex    6000                2
4         105  Farida      Sales  Cairo    7200                4
6         107    Mona         HR   Alex    6100                1
7         108   Karim      Sales  Cairo    7300                3
9         102    Omar      Sales   Giza    7000                3

   PerformanceScore
1              75.0
3              65.0
4              90.0
6              70.0
7              82.0
9              75.0
   EmployeeID     Name Department  City  Salary  YearsExperience  \
1         102     Omar      Sales  Giza    7000                3
3         104    Ahmed         HR  Alex    6000                2
5         106  Youssef         IT  Giza    9500                7
6         107     Mona         HR  Alex    6100                1
8         109    Salma         IT  Giza    8800                5
9         102     Omar      Sales  Giza    7000                3

   PerformanceScore
1              75.0
3              65.0
5               NaN
6              70.0
8               NaN
9              75.0
   EmployeeID     Name Department   City  Salary  YearsExperience  \
0         101     Sara         IT  Cairo    9000                5
5         106  Youssef         IT   Giza    9500                7
8         109    Salma         IT   Giza    8800                5

   PerformanceScore
0              88.0
5               NaN
8               NaN

## 7. Sorting Data

In [50]:
df.sort_values("Salary")                        # ascending by default

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
3,104,Ahmed,HR,Alex,6000,2,65.0
6,107,Mona,HR,Alex,6100,1,70.0
1,102,Omar,Sales,Giza,7000,3,75.0
9,102,Omar,Sales,Giza,7000,3,75.0
4,105,Farida,Sales,Cairo,7200,4,90.0
7,108,Karim,Sales,Cairo,7300,3,82.0
2,103,Lina,IT,Cairo,8500,6,NaN
8,109,Salma,IT,Giza,8800,5,NaN
0,101,Sara,IT,Cairo,9000,5,88.0
5,106,Youssef,IT,Giza,9500,7,NaN

In [51]:
df.sort_values("Salary", ascending=False)       # highest paid first

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
5,106,Youssef,IT,Giza,9500,7,NaN
0,101,Sara,IT,Cairo,9000,5,88.0
8,109,Salma,IT,Giza,8800,5,NaN
2,103,Lina,IT,Cairo,8500,6,NaN
7,108,Karim,Sales,Cairo,7300,3,82.0
4,105,Farida,Sales,Cairo,7200,4,90.0
1,102,Omar,Sales,Giza,7000,3,75.0
9,102,Omar,Sales,Giza,7000,3,75.0
6,107,Mona,HR,Alex,6100,1,70.0
3,104,Ahmed,HR,Alex,6000,2,65.0

In [52]:
df.sort_values(["Department", "Salary"], ascending=[True, False])
# sort by Department A-Z, and within each department, highest salary first

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
6,107,Mona,HR,Alex,6100,1,70.0
3,104,Ahmed,HR,Alex,6000,2,65.0
5,106,Youssef,IT,Giza,9500,7,NaN
0,101,Sara,IT,Cairo,9000,5,88.0
8,109,Salma,IT,Giza,8800,5,NaN
2,103,Lina,IT,Cairo,8500,6,NaN
7,108,Karim,Sales,Cairo,7300,3,82.0
4,105,Farida,Sales,Cairo,7200,4,90.0
1,102,Omar,Sales,Giza,7000,3,75.0
9,102,Omar,Sales,Giza,7000,3,75.0

In [53]:
by_salary = df.sort_values("Salary", ascending=False)
print("row labels after sorting by value:", by_salary.index.tolist())

print("\nsorted back by original row label (index):")
by_salary.sort_index()

row labels after sorting by value: [5, 0, 8, 2, 7, 4, 1, 9, 6, 3]

sorted back by original row label (index):

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore
0,101,Sara,IT,Cairo,9000,5,88.0
1,102,Omar,Sales,Giza,7000,3,75.0
2,103,Lina,IT,Cairo,8500,6,NaN
3,104,Ahmed,HR,Alex,6000,2,65.0
4,105,Farida,Sales,Cairo,7200,4,90.0
5,106,Youssef,IT,Giza,9500,7,NaN
6,107,Mona,HR,Alex,6100,1,70.0
7,108,Karim,Sales,Cairo,7300,3,82.0
8,109,Salma,IT,Giza,8800,5,NaN
9,102,Omar,Sales,Giza,7000,3,75.0

**✍️ Practice 7**
1. Sort `df` by `YearsExperience` descending.
2. Sort by `Department` then `Name` (both ascending).
3. Take the result of (1) and restore the original row order with `sort_index()`.

In [55]:
# ✅ solution
r1 = df.sort_values("YearsExperience", ascending=False)
print(r1)
print(df.sort_values(["Department", "Name"]))
print(r1.sort_index())

   EmployeeID     Name Department   City  Salary  YearsExperience  \
5         106  Youssef         IT   Giza    9500                7
2         103     Lina         IT  Cairo    8500                6
8         109    Salma         IT   Giza    8800                5
0         101     Sara         IT  Cairo    9000                5
4         105   Farida      Sales  Cairo    7200                4
1         102     Omar      Sales   Giza    7000                3
9         102     Omar      Sales   Giza    7000                3
7         108    Karim      Sales  Cairo    7300                3
3         104    Ahmed         HR   Alex    6000                2
6         107     Mona         HR   Alex    6100                1

   PerformanceScore
5               NaN
2               NaN
8               NaN
0              88.0
4              90.0
1              75.0
9              75.0
7              82.0
3              65.0
6              70.0
   EmployeeID     Name Department   City  Salary  YearsExperience  \
3         104    Ahmed         HR   Alex    6000                2
6         107     Mona         HR   Alex    6100                1
2         103     Lina         IT  Cairo    8500                6
8         109    Salma         IT   Giza    8800                5
0         101     Sara         IT  Cairo    9000                5
5         106  Youssef         IT   Giza    9500                7
4         105   Farida      Sales  Cairo    7200                4
7         108    Karim      Sales  Cairo    7300                3
1         102     Omar      Sales   Giza    7000                3
9         102     Omar      Sales   Giza    7000                3

   PerformanceScore
3              65.0
6              70.0
2               NaN
8               NaN
0              88.0
5               NaN
4              90.0
7              82.0
1              75.0
9              75.0
   EmployeeID     Name Department   City  Salary  YearsExperience  \
0         101     Sara         IT  Cairo    9000                5
1         102     Omar      Sales   Giza    7000                3
2         103     Lina         IT  Cairo    8500                6
3         104    Ahmed         HR   Alex    6000                2
4         105   Farida      Sales  Cairo    7200                4
5         106  Youssef         IT   Giza    9500                7
6         107     Mona         HR   Alex    6100                1
7         108    Karim      Sales  Cairo    7300                3
8         109    Salma         IT   Giza    8800                5
9         102     Omar      Sales   Giza    7000                3

   PerformanceScore
0              88.0
1              75.0
2               NaN
3              65.0
4              90.0
5               NaN
6              70.0
7              82.0
8               NaN
9              75.0

## 8. Creating & Modifying Columns

In [56]:
df["Bonus"] = df["Salary"] * 0.1        # vectorized -- applied to the whole column at once
df[["Name", "Salary", "Bonus"]]

      Name  Salary  Bonus
0     Sara    9000  900.0
1     Omar    7000  700.0
2     Lina    8500  850.0
3    Ahmed    6000  600.0
4   Farida    7200  720.0
5  Youssef    9500  950.0
6     Mona    6100  610.0
7    Karim    7300  730.0
8    Salma    8800  880.0
9     Omar    7000  700.0

In [57]:
df["SalaryK"] = df["Salary"] / 1000
df[["Name", "Salary", "SalaryK"]]

      Name  Salary  SalaryK
0     Sara    9000      9.0
1     Omar    7000      7.0
2     Lina    8500      8.5
3    Ahmed    6000      6.0
4   Farida    7200      7.2
5  Youssef    9500      9.5
6     Mona    6100      6.1
7    Karim    7300      7.3
8    Salma    8800      8.8
9     Omar    7000      7.0

In [58]:
df_renamed = df.rename(columns={"Salary": "BaseSalary"})
print(df_renamed.columns.tolist())
print("original df still has 'Salary':", "Salary" in df.columns)   # rename() returns a NEW df

['EmployeeID', 'Name', 'Department', 'City', 'BaseSalary', 'YearsExperience', 'PerformanceScore', 'Bonus', 'SalaryK']
original df still has 'Salary': True

In [59]:
df_no_city = df.drop(columns=["City"])
print(df_no_city.columns.tolist())
print("original df still has 'City':", "City" in df.columns)       # drop() also returns a NEW df

['EmployeeID', 'Name', 'Department', 'Salary', 'YearsExperience', 'PerformanceScore', 'Bonus', 'SalaryK']
original df still has 'City': True

In [60]:
print("before:", df["YearsExperience"].dtype)
df["YearsExperience"] = df["YearsExperience"].astype(float)
print("after :", df["YearsExperience"].dtype)

before: int64
after : float64

**✍️ Practice 8**
1. Create a new column `SalaryAfterRaise` = `Salary * 1.05`.
2. Rename `City` to `Location` (in a new DataFrame, don't overwrite `df`).
3. Drop the `SalaryK` column (in a new DataFrame).
4. Convert `EmployeeID` to `str` dtype and confirm with `.dtype`.

In [62]:
# ✅ solution
df["SalaryAfterRaise"] = df["Salary"] * 1.05
df_loc = df.rename(columns={"City": "Location"})
print(df_loc.columns.tolist())
df_drop = df.drop(columns=["SalaryK"])
print(df_drop.columns.tolist())
eid_str = df["EmployeeID"].astype(str)
print(eid_str.dtype)

['EmployeeID', 'Name', 'Department', 'Location', 'Salary', 'YearsExperience', 'PerformanceScore', 'Bonus', 'SalaryK', 'SalaryAfterRaise']
['EmployeeID', 'Name', 'Department', 'City', 'Salary', 'YearsExperience', 'PerformanceScore', 'Bonus', 'SalaryAfterRaise']
str

## 9. Missing Data

`NaN` ("Not a Number") is Pandas' placeholder for missing/undefined values.

In [63]:
df.isna().sum()      # count of missing values PER COLUMN

EmployeeID          0
Name                0
Department          0
City                0
Salary              0
YearsExperience     0
PerformanceScore    3
Bonus               0
SalaryK             0
SalaryAfterRaise    0
dtype: int64

In [64]:
df[df["PerformanceScore"].isna()]     # show just the affected rows

,EmployeeID,Name,Department,City,Salary,YearsExperience,PerformanceScore,Bonus,SalaryK,SalaryAfterRaise
2,103,Lina,IT,Cairo,8500,6.0,NaN,850.0,8.5,8925.0
5,106,Youssef,IT,Giza,9500,7.0,NaN,950.0,9.5,9975.0
8,109,Salma,IT,Giza,8800,5.0,NaN,880.0,8.8,9240.0

In [65]:
df["PerformanceScore"].notna().sum()   # count of NON-missing values

np.int64(7)

In [66]:
# fillna -- fill with a constant
df["PerformanceScore_filled0"] = df["PerformanceScore"].fillna(0)

# fillna -- fill with the column mean (more realistic for a score)
df["PerformanceScore_filledMean"] = df["PerformanceScore"].fillna(df["PerformanceScore"].mean())

df[["Name", "PerformanceScore", "PerformanceScore_filled0", "PerformanceScore_filledMean"]]

,Name,PerformanceScore,PerformanceScore_filled0,PerformanceScore_filledMean
0,Sara,88.0,88.0,88.000000
1,Omar,75.0,75.0,75.000000
2,Lina,NaN,0.0,77.857143
3,Ahmed,65.0,65.0,65.000000
4,Farida,90.0,90.0,90.000000
5,Youssef,NaN,0.0,77.857143
6,Mona,70.0,70.0,70.000000
7,Karim,82.0,82.0,82.000000
8,Salma,NaN,0.0,77.857143
9,Omar,75.0,75.0,75.000000

In [67]:
# forward fill -- carry the previous valid value forward
sample_series = pd.Series([10, np.nan, np.nan, 20, np.nan])
print(sample_series.ffill())     # modern equivalent of fillna(method="ffill")

0    10.0
1    10.0
2    10.0
3    20.0
4    20.0
dtype: float64

In [68]:
# dropna -- remove rows/columns with any missing value
print("before dropna:", df.shape)
df_complete_cases = df.dropna(subset=["PerformanceScore"])
print("after dropna (subset=PerformanceScore):", df_complete_cases.shape)

df_no_missing_cols = df.dropna(axis=1)      # drop any COLUMN that has at least one NaN
print("columns remaining after dropna(axis=1):", df_no_missing_cols.columns.tolist())

before dropna: (10, 12)
after dropna (subset=PerformanceScore): (7, 12)
columns remaining after dropna(axis=1): ['EmployeeID', 'Name', 'Department', 'City', 'Salary', 'YearsExperience', 'Bonus', 'SalaryK', 'SalaryAfterRaise', 'PerformanceScore_filled0', 'PerformanceScore_filledMean']

**💬 Discussion:** if only 3 rows out of 10 are missing `PerformanceScore`, is it better to `fillna()` or `dropna()`? What if it were 3 out of 1000?

**✍️ Practice 9**
1. Count total missing values in the whole DataFrame (one number).
2. Fill missing `PerformanceScore` with the **median** instead of the mean.
3. Drop rows where `PerformanceScore` is missing, and confirm the new shape.

In [70]:
# ✅ solution
print("total missing:", df.isna().sum().sum())
median_fill = df["PerformanceScore"].fillna(df["PerformanceScore"].median())
print(median_fill)
dropped = df.dropna(subset=["PerformanceScore"])
print(dropped.shape)

total missing: 3
0    88.0
1    75.0
2    75.0
3    65.0
4    90.0
5    75.0
6    70.0
7    82.0
8    75.0
9    75.0
Name: PerformanceScore, dtype: float64
(7, 12)

## ✅ End of Part 1

**Covered so far:** Introduction → Series & DataFrame (creation, attributes) → Reading Data → Exploring → Selecting → Filtering → Sorting → Creating/Modifying Columns → Missing Data.

**Coming in Part 2:** Duplicate Data → GroupBy & Aggregation → Combining DataFrames (merge/concat) → Pivot Tables → apply() → map() → `value_counts()`/`unique()`/`nunique()` → Final Titanic Mini Project.